name = "LocalisedLiterals"
uuid = "995de36e-601e-4c1e-a619-888650660daa"
authors = ["Henrik Wolf <henrik-wolf@freenet.de> and contributors"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
HTTP = "1"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
